### ISSUE TITLE
请问image转换为tenosr输入模型时出现错误是什么情况？数据类型错误？

### ISSUE THREAD

**Issue by dingjianfei** [xionghc/Facial-Expression-Recognition#4]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1068, in _run
    allow_operation=False)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 2708, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 2797, in _as_graph_element_locked
    % (type(obj).__name__, types_str))
TypeError: Can not convert a int32 into a Tensor.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 36, in <module>
    main()
  File "main.py", line 29, in main
    run_demo(args)
  File "main.py", line 7, in run_demo
    demo(args.modelPath, args.showbox)
  File "/home/d/Facial-Expression-Recognition/Facial-Expression-Recognition-master/demo.py", line 119, in demo
    result = sess.run(probs, feed_dict={x: tensor})
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1071, in _run
    + e.args[0])
TypeError: Cannot interpret feed_dict key as Tensor: Can not convert a int32 into a Tensor.

**Comment by xionghc** [comment]
你应该是改了我的代码吧？我的代码demo.py第119行不是result = sess.run(probs, feed_dict={x: tensor})

**Comment by dingjianfei** [comment]
用源码也是的，第一次运行正常，第二次就会出现这种情况。

**Comment by xionghc** [comment]
我的代码应该不存在这个问题啊。

**Comment by LPaKing** [comment]
那你原来的代码是什么？现在的119行代码就是result = sess.run(probs, feed_dict={x: tensor})

**Comment by LPaKing** [comment]
我的也是出现这样的错误

**Comment by xionghc** [comment]
@LPaKing 很多人和我说了这个问题，但是我一直查不出原因。

**Comment by xionghc** [comment]
@LPaKing 很多人和我说了这个问题，但是我自己没法复现这个错误，也找不出原因。

**Comment by LPaKing** [comment]
我知道什么问题了，代码placehoder的x变量改个名字就好了

**Comment by LPaKing** [comment]
我知道什么问题了，代码placehoder的x变量改个名字就好了

**Comment by LPaKing** [comment]
result = sess.run(probs, feed_dict={x: tensor})这里x也要相应改掉

**Comment by xionghc** [comment]
@LPaKing 非常感谢，这个x和坐标的x重名了，非常感谢。你可以把你的修改pull request，我合并进来

**Comment by xionghc** [comment]
最新提交已解决该问题。
