### ISSUE TITLE
Cannot interpret feed_dict key as Tensor: Can not convert a int32 into a Tensor.

### ISSUE THREAD

**Issue by hansolkang** [xionghc/Facial-Expression-Recognition#5]
Traceback (most recent call last):
  File "main.py", line 36, in <module>
    main()
  File "main.py", line 29, in main
    run_demo(args)
  File "main.py", line 7, in run_demo
    demo(args.modelPath, args.showbox)
  File "/home/hci/hansol/cantexecutewell/demo.py", line 110, in demo
    result = sess.run(probs, feed_dict={x: tensor})
  File "/home/hci/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/home/hci/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1067, in _run
    + e.args[0])
TypeError: Cannot interpret feed_dict key as Tensor: Can not convert a int32 into a Tensor.

Hello. It didn't work it. I had typing "python3 main.py demo ./models"  and only my face appear and insert "SPACE" then have above message. How can I try that? Help me plz.

**Comment by xionghc** [comment]
@hansolkang Others have encountered the same problem.  I inspect my code, and test my program again and again, this problem can't reappear. I don't know what happen.

**Comment by xionghc** [comment]
This issue have been solved. See as #4 .
